# Generated by Django 5.0.6 on 2025-10-24 04:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_tags', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Например: AAPL, MSFT, GOOGL', max_length=10, verbose_name='Тикер акции')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Название компании')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Количество акций')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена покупки за акцию')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='finance.currency', verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_stocks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
