# Generated by Django 5.2.7 on 2025-10-26 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_historicalaccount_historicalbudget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления тега')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Добавлено пользователем')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tag', verbose_name='Тег')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'Тег транзакции',
                'verbose_name_plural': 'Теги транзакций',
                'unique_together': {('transaction', 'tag')},
            },
        ),
    ]
