# Generated by Django 5.2.7 on 2025-10-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transactiontag'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='attachment',
            field=models.TextField(blank=True, help_text='Прикрепленный документ (договор, счет, накладная и т.д.)', max_length=100, null=True, verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='stock',
            name='company_website',
            field=models.URLField(blank=True, help_text='URL официального сайта компании', max_length=500, verbose_name='Сайт компании'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='attachment',
            field=models.FileField(blank=True, help_text='Прикрепленный документ (договор, счет, накладная и т.д.)', null=True, upload_to='transaction_documents/%Y/%m/', verbose_name='Документ'),
        ),
    ]
